eigen_abi_profile:
  - 100
  - 80  # [x86_64 and not win]
  - 70  # [x86_64 and not win]

eigen_max_align_bytes:
  - 16
  - 32  # [x86_64 and not win]
  - 64  # [x86_64 and not win]

zip_keys:
  - 
    - eigen_abi_profile
    - eigen_max_align_bytes
